const maxima = { 'Emotional Health': 24, 'Stress & Anxiety': 24, 'Sleep & Energy': 20, 'Social Connection': 20, 'Daily Functioning': 20 };
export const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

export function renderReport(report) {
  const e = escapeHtml;
  const person = report.user_details;
  const feedback = report.total_score <= 35
    ? 'Your responses fall in the lower range of this screening. Continue checking in with yourself and maintaining habits that support your wellbeing.'
    : report.total_score <= 70
      ? 'Your responses suggest some areas may need attention. Consider discussing your concerns with someone you trust or a qualified health professional.'
      : 'Your responses suggest additional support may be helpful. Consider contacting a qualified health professional soon.';
  const rows = Object.entries(maxima).map(([name, max]) => {
    const score = Number(report.domain_scores[name]) || 0;
    const percent = Math.max(0, Math.min(100, score / max * 100));
    return `<tr><th scope="row">${e(name)}</th><td>${score} / ${max}</td><td><div class="track" role="img" aria-label="${e(name)}: ${score} out of ${max}"><div style="width:${percent}%"></div></div></td><td>${Math.round(percent)}%</td></tr>`;
  }).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>WellBeingCheck report</title><style>
  *{box-sizing:border-box}body{font:16px/1.6 system-ui,sans-serif;color:#193844;background:#edf5f5;margin:0;padding:32px}main{max-width:900px;margin:auto;background:white;padding:40px;border-radius:16px}h1{font-size:32px;margin:8px 0}h2{font-size:21px;margin-top:28px}header{border-bottom:3px solid #167a79;padding-bottom:20px}.brand{color:#167a79;font-weight:700;letter-spacing:2px}.details{display:grid;grid-template-columns:1fr 1fr;gap:8px 28px;overflow-wrap:anywhere}.summary{background:#eaf5f4;padding:20px;margin:24px 0;border-radius:10px}.score{font-size:38px;font-weight:700}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:12px 6px;border-bottom:1px solid #dce7e8}td:nth-child(3){width:35%}.track{height:14px;background:#e3ebed;border-radius:7px;overflow:hidden}.track div{height:100%;background:#167a79}small,footer{color:#536a73}a{color:#126b71}footer{margin-top:28px;border-top:1px solid #dce7e8;padding-top:16px;font-size:13px}section{break-inside:avoid}@media(max-width:600px){body{padding:8px}main{padding:20px}.details{grid-template-columns:1fr}th,td{font-size:13px}}@media print{body{background:white;padding:0;font-size:11pt}main{padding:0;max-width:none}.print-note{display:none}h1{font-size:24pt}.summary{print-color-adjust:exact}.track{print-color-adjust:exact}a{color:inherit}@page{size:A4;margin:16mm}}
  </style></head><body><main><header><div class="brand">WELLBEINGCHECK</div><h1>Personal wellbeing report</h1><div>Assessment completed: ${e(new Date(report.completed_at).toLocaleString('en-AU', { timeZone: 'UTC' }))} UTC</div><small>Report ${e(report.id)} · Version ${e(report.version)}</small></header>
  <p class="print-note">To save as PDF, use your browser’s Print menu and choose “Save as PDF”.</p>
  <section><h2>User details</h2><div class="details"><div><strong>Name:</strong> ${e([person.firstName, person.lastName].filter(Boolean).join(' ') || 'Not provided')}</div><div><strong>Email:</strong> ${e(person.email || 'Not provided')}</div><div><strong>Phone:</strong> ${e(person.phone || 'Not provided')}</div><div><strong>User ID:</strong> ${e(report.user_id)}</div></div></section>
  <section class="summary"><div class="score">${e(report.total_score)} / 108</div><strong>Screening category: ${e(report.risk_level)}</strong><p>${e(feedback)}</p></section>
  <section><h2>Score chart and breakdown</h2><p>Higher scores indicate more reported concerns under the app’s current scoring method. Percentages show points out of each domain’s maximum, not a probability of illness.</p><table><thead><tr><th>Domain</th><th>Score</th><th>Score chart</th><th>Percent</th></tr></thead><tbody>${rows}</tbody></table><small>Categories: 0–35 No Risk; 36–70 Borderline; 71–108 At Risk. These are app-defined screening categories, not clinical diagnoses. “No Risk” does not rule out a concern.</small></section>
  <section><h2>Feedback and next steps</h2><ul><li>Reflect on the domains with the highest percentage scores and how they affect your day.</li><li>Consider sharing this report with a GP or qualified mental health professional, especially if concerns persist or affect daily life.</li><li>Reach out to someone you trust for support. Seek help whenever you need it, regardless of your score.</li></ul></section>
  <section><h2>Help and contact information</h2><p>Australia: If life is in immediate danger, call <strong>000</strong>. Outside Australia, contact your local emergency service.</p><ul><li><a href="https://www.lifeline.org.au/get-help/national-services/lifeline-crisis-support">Lifeline crisis support</a>: <strong>13 11 14</strong></li><li><a href="https://www.beyondblue.org.au/get-support">Beyond Blue support</a>: <strong>1300 22 4636</strong></li></ul><p>These contacts serve Australia. If you live elsewhere, use a local health provider or crisis support service.</p></section>
  <footer>Private health information. Share only with people you choose. This report reflects self-reported assessment responses and is not a medical diagnosis. Profile details are captured when the report is created. Generated ${e(new Date(report.generated_at).toISOString())}.</footer></main></body></html>`;
}
